// place files you want to import through the `$lib` alias in this folder.
export const clubs = [
	'Shaughnessy Golf & Country Club',
	'Capilano Golf & Country Club',
	'Marine Drive Golf Club',
	'Point Grey Golf & Country Club',
	'Vancouver Golf Club',
	'Quilchena Golf & Country Club',
	'Richmond Golf & Tennis Country Club',
	'Victoria Golf Club',
	'Royal Mayfair Golf Club',
	'Priddis Greens Golf & Country Club',
	'Edmonton Petroleum Golf & Country Club',
	'Edmonton Country Club',
	'Country Hills Golf Club',
	'Canyon Meadows Golf & Country Club',
	'Wascana Country Club',
	'Riverside Country Club',
	'Greenbryre Golf & Country Club',
	'The Willows Golf & Country Club',
	'Niakwa Country Club',
	'St. Charles Country Club',
	'Elmhurst Golf & Country Club',
	'Pine Ridge Golf Club',
	'Southwood Golf & Country Club',
	'Glendale Golf & Country Club',
	'Oakville Golf Club',
	'Essex Golf & Country Club',
	"King's Riding Golf Club",
	'Toronto Golf Club',
	'Scarboro Golf & Country Club',
	'Lookout Point Country Club',
	'Beverly Golf & Country Club',
	'The Briars Golf Club',
	'The Royal Montreal Golf Club',
	'Mount Bruno Country Club',
	'Le Club Laval-sur-le-Lac',
	'Club de golf Le Mirage',
	'Le Balmoral (Club de Golf Le Balmoral)',
	"Club de Golf de l'Île de Montréal",
	'Rivermead Golf Club',
	'Club de golf Royal Québec',
	'Larrimac Golf & Tennis Club',
	'Fox Creek Golf Club',
	'Riverside Country Club',
	'Ashburn Golf Club',
	'Dalhousie Golf Club'
];

